import React from 'react';
import ProductoRnd from '../ProductoRnd/ProductoRnd';
import './ProductoLista.css';

export const Productos = [
  { id: 1, imagen: "/catalogo-siempremates//img/Mate-camionero1.png", nombre: "Mate camionero de algarrobo con virola de acero inox. ", precio: "25.000", categoria: "Mates", descripcion: "El mate camionero de algarrobo con virola de acero inoxidable combina la rusticidad y calidez de la madera con la resistencia y durabilidad del acero inoxidable. La madera de algarrobo mantiene la temperatura del mate por más tiempo, mientras que la virola de acero le da una mayor resistencia al desgaste y la corrosión. Su diseño grande es ideal para aquellos que disfrutan de un mate prolongado, especialmente en viajes largos. Es fácil de mantener, estéticamente atractivo y perfecto para quienes buscan durabilidad y estilo en su rutina de mate." },
  { id: 2, imagen: "/catalogo-siempremates//img/Mate-camionero2.png", nombre: "Mate camionero int calabza con virola de acero", precio: "25.000", categoria: "Mates", descripcion: "El mate camionero de interior de calabaza con virola de acero es una opción clásica y resistente para los amantes del mate. La calabaza, un material natural, ofrece una experiencia única al beber, ya que absorbe los sabores con el tiempo, mejorando con cada uso. La virola de acero inoxidable refuerza la base, evitando que la calabaza se desgaste o rompa fácilmente, y le da un toque moderno y duradero. Este tipo de mate es ideal para quienes buscan una mayor capacidad, ya que su diseño más grande permite disfrutar de varias rondas de mate sin necesidad de recargar constantemente. Además, el acero inoxidable ayuda a mantener la integridad del mate, protegiendo la calabaza de posibles daños. Es una opción perfecta para quienes viajan mucho o para aquellos que prefieren un mate más robusto, con un equilibrio entre tradición y funcionalidad." },
  { id: 3, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza1.png", nombre: "Mate Imperial int. calabaza con virola de acero inoxidable", precio: "28.500", categoria: "Mates", descripcion: "El mate Imperial de interior de calabaza con virola de acero inoxidable combina lo mejor de la tradición y la durabilidad. La calabaza proporciona una experiencia auténtica, mejorando con el uso y adaptándose al sabor del mate. La virola de acero inoxidable refuerza la estructura del mate, evitando daños y garantizando una mayor resistencia. Su tamaño y diseño permiten disfrutar de un mate más grande, ideal para quienes buscan comodidad y durabilidad sin sacrificar el estilo clásico del mate tradicional. Perfecto para quienes valoran tanto la estética como la funcionalidad en su rutina de mate." },
  { id: 4, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza2.png", nombre: "Mate imperial int. calabaza con virola de alpaca ", precio: "34.500", categoria: "Mates", descripcion: "El mate Imperial de interior de calabaza con virola de alpaca es una opción elegante y funcional para los amantes del mate. La calabaza, por su parte, ofrece una experiencia auténtica, mejorando su sabor con el tiempo. La virola de alpaca le da un toque distintivo, brindando resistencia y un acabado brillante, a la vez que protege la calabaza de posibles daños. Su diseño grande es ideal para disfrutar de largas sesiones de mate, combinando tradición y durabilidad en un solo accesorio. Perfecto para quienes buscan un mate sofisticado y de calidad." },
  { id: 5, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza3.png", nombre: "Mate imperial int. calabaza con base reforzada y virola de alpaca", precio: "35.500", categoria: "Mates", descripcion: "El mate Imperial de interior de calabaza con base reforzada y virola de alpaca es una opción robusta y elegante para quienes buscan calidad en su experiencia de mate. La calabaza ofrece un sabor auténtico que mejora con el uso, mientras que la base reforzada asegura mayor estabilidad y durabilidad. La virola de alpaca le da un toque sofisticado, protegiendo la calabaza y garantizando resistencia al desgaste. Su diseño grande permite disfrutar de varias rondas de mate, combinando funcionalidad, tradición y un acabado refinado que lo convierte en una excelente elección para cualquier amante del mate." },
  { id: 6, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza4.png", nombre: "Mate imperial int.calabaza animal print con virola de alpaca", precio: "100.000", categoria: "Mates", descripcion: "El mate Imperial de interior de calabaza con diseño animal print y virola de alpaca es una opción única y moderna para quienes buscan un toque de estilo en su rutina de mate. La calabaza ofrece un sabor auténtico y mejora con el tiempo, mientras que el diseño animal print aporta un toque original y llamativo. La virola de alpaca le da una mayor resistencia y un acabado brillante, protegiendo la calabaza de posibles daños. Este mate combina la tradición con un diseño audaz y sofisticado, ideal para quienes desean algo diferente y elegante." },
  { id: 7, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza5.png", nombre: "Mate imperial int. calabaza con base reforzada y virola de alpaca y bolitas de bronce ", precio: "58.000", categoria: "Mates", descripcion: "El mate Imperial de interior de calabaza con base reforzada, virola de alpaca y bolitas de bronce es una opción única que combina resistencia, elegancia y detalles artesanales. La calabaza proporciona una experiencia auténtica, mejorando su sabor con el tiempo, mientras que la base reforzada le otorga estabilidad y durabilidad. La virola de alpaca le da un toque sofisticado, mientras que las bolitas de bronce agregan un detalle especial que hace que cada mate sea único. Este diseño combina lo clásico con elementos modernos, ideal para quienes buscan un mate robusto y estilizado." },
  { id: 8, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza6.png", nombre: "Mate imperial croco int calabaza y base reforzada de alpaca ", precio: "50.000", categoria: "Mates", descripcion: "El mate Imperial croco de interior de calabaza con base reforzada de alpaca es una opción elegante y duradera para los amantes del mate. El diseño croco en la calabaza le da un toque sofisticado y distintivo, mientras que la calabaza mantiene el sabor auténtico del mate y mejora con el uso. La base reforzada de alpaca aporta resistencia y estabilidad, protegiendo la calabaza y garantizando una mayor durabilidad. Este mate combina estética, funcionalidad y tradición, convirtiéndolo en una excelente opción para quienes buscan un mate robusto y de estilo refinado." },
  { id: 9, imagen: "/catalogo-siempremates//img/Mate-imperial-calabaza7.png", nombre: "Mate imperial repujado int. calabaza con virola de alpaca ", precio: "40.000", categoria: "Mates", descripcion: "El mate Imperial repujado de interior de calabaza con virola de alpaca es una opción elegante y artesanal para los amantes del mate. La calabaza ofrece un sabor auténtico que mejora con el tiempo, mientras que el repujado en su exterior le da un toque detallado y único. La virola de alpaca refuerza la estructura del mate, brindando una mayor resistencia y un acabado brillante que lo hace aún más atractivo. Este mate combina la tradición con la estética artesanal, ideal para quienes buscan un producto de calidad y con un diseño distintivo." },
  { id: 10, imagen: "/catalogo-siempremates//img/Mate-torpedo1.png", nombre: "Mate torpedo int. calabaza con virola de alpaca cincelada", precio: "30.000", categoria: "Mates", descripcion: "El mate torpedo de interior de calabaza con virola de alpaca cincelada es una opción única que combina la tradición con detalles artesanales de gran elegancia. La calabaza proporciona una experiencia auténtica y mejora con el uso, mientras que la virola de alpaca cincelada ofrece un acabado sofisticado y detallado, agregando un toque de distinción al diseño. El formato torpedo le da un estilo moderno y cómodo para tomar mate, mientras que la virola refuerza la durabilidad y resistencia del mate. Ideal para quienes buscan una combinación de funcionalidad, estética y calidad en su rutina de mate." },
  { id: 11, imagen: "/catalogo-siempremates//img/Mate-torpedo2.png", nombre: "Mate torpedo int. calabaza con virola cincelada", precio: "33.000", categoria: "Mates", descripcion: "El mate torpedo de interior de calabaza con virola cincelada es una opción elegante y funcional para quienes buscan una experiencia de mate única. La calabaza, además de ofrecer un sabor auténtico, mejora con el uso, mientras que la virola cincelada agrega un toque artesanal y sofisticado al diseño. El formato torpedo, cómodo y estilizado, hace que este mate sea ideal para largas sesiones de mate. La virola refuerza la estructura, garantizando durabilidad y resistencia, lo que convierte a este mate en una excelente opción para los amantes del mate que valoran la estética y la calidad." },
  { id: 12, imagen: "/catalogo-siempremates//img/Mate-torpedo3.png", nombre: "Mate torpedo int calabza con viorola cincelada y base reforzada de alpaca con pelotitas de bronce ", precio: "57.000", categoria: "Mates", descripcion: "El mate torpedo de interior de calabaza con virola cincelada y base reforzada de alpaca con pelotitas de bronce es una pieza de gran elegancia y resistencia. La calabaza ofrece un sabor auténtico que mejora con el tiempo, mientras que la virola cincelada le da un toque artesanal y sofisticado. La base reforzada de alpaca proporciona estabilidad y durabilidad, y las pelotitas de bronce añaden un detalle decorativo único que hace que cada mate sea especial. Ideal para quienes buscan un mate robusto, con un diseño refinado y detalles que combinan tradición y estilo." },
  { id: 13, imagen: "/catalogo-siempremates//img/Mate-torpedo4.png", nombre: "Mate torpedo int. acero inox y viola de acero inox ", precio: "23.000", categoria: "Mates", descripcion: "El mate torpedo de interior de acero inoxidable con virola de acero inoxidable es una opción moderna, duradera y fácil de mantener. El acero inoxidable en el interior asegura que el mate no absorba sabores, permitiendo una experiencia limpia y auténtica en cada uso. La virola de acero inoxidable refuerza la estructura del mate, proporcionando una mayor resistencia y un acabado brillante. Con su diseño torpedo, este mate combina funcionalidad y estilo, siendo ideal para quienes buscan durabilidad, practicidad y un toque de modernidad en su rutina de mate." },
  { id: 14, imagen: "/catalogo-siempremates//img/Mate-torpedo5.png", nombre: "Mate torpedo algarrobo y virola de alpaca cincelada", precio: "29.000", categoria: "Mates", descripcion: "El mate torpedo de algarrobo con virola de alpaca cincelada es una opción que fusiona la calidez de la madera con la elegancia del metal. El algarrobo, conocido por su durabilidad y aspecto rústico, le da al mate una textura y un color únicos, mientras que la virola de alpaca cincelada agrega un toque sofisticado y detallado al diseño. El formato torpedo proporciona comodidad y un agarre ergonómico, mientras que la combinación de materiales asegura un mate robusto y estéticamente atractivo, perfecto para quienes buscan tradición con un toque de distinción." },
  { id: 15, imagen: "/catalogo-siempremates//img/Mate-torpedo6.png", nombre: "Mate torpedo animal print int calabaza y virola de alpaca", precio: "45.000", categoria: "Mates", descripcion: "El mate torpedo animal print de interior de calabaza con virola de alpaca es una opción única que combina un diseño audaz con la tradición. La calabaza ofrece una experiencia auténtica, mejorando con el tiempo y adaptándose al sabor del mate, mientras que el diseño animal print en su exterior agrega un toque moderno y llamativo. La virola de alpaca le da un acabado sofisticado y resistente, protegiendo la calabaza y garantizando mayor durabilidad. Ideal para quienes buscan un mate diferente, elegante y con un toque de estilo único en su rutina diaria." },
  { id: 16, imagen: "/catalogo-siempremates//img/Mate-torpedo7.jpg", nombre: "Mate torpedo virola  y base de alpaca con pelotitas de bronce", precio: "57.000", categoria: "Mates", descripcion: "El mate torpedo con virola y base de alpaca con pelotitas de bronce es una pieza elegante y robusta, ideal para quienes buscan calidad y estilo. La virola de alpaca proporciona un acabado brillante y resistente, mientras que la base de alpaca refuerza la estructura, garantizando estabilidad y durabilidad. Las pelotitas de bronce añaden un detalle decorativo único que destaca su diseño. Con su forma torpedo, es cómodo para sostener y perfecto para disfrutar de un mate prolongado, combinando tradición y modernidad en un solo accesorio." },
  { id: 17, imagen: "/catalogo-siempremates//img/Mate-torpedo8.jpg", nombre: "", precio: "45.000", categoria: "Mates", descripcion: "" },
  { id: 18, imagen: "/catalogo-siempremates//img/Mate-imperial-inoxidable.png", nombre: "Mate imperial int. acero inoxidale con virola de acero ", precio: "30.000", categoria: "Mates", descripcion: "El mate Imperial de interior de acero inoxidable con virola de acero es una opción moderna y duradera para quienes buscan practicidad y estilo. El acero inoxidable en su interior mantiene el sabor del mate limpio y auténtico, mientras que la virola de acero refuerza la estructura, aportando resistencia y un acabado brillante. Su diseño elegante y funcional lo hace ideal para disfrutar del mate de manera cómoda y estilizada, siendo fácil de mantener y perfecto para quienes prefieren materiales duraderos y contemporáneos en su rutina diaria." },
  { id: 19, imagen: "/catalogo-siempremates//img/Mate-imperial-algarrobo.png", nombre: "Torpedo virola de alpaca cincelada premium", precio: "28.000", categoria: "Mates", descripcion: "El mate torpedo con virola de alpaca cincelada premium es una pieza de alta gama que combina elegancia y durabilidad. La forma torpedo ofrece un agarre cómodo y un diseño estilizado, mientras que la virola cincelada de alpaca le da un toque sofisticado y artesanal. Esta virola no solo aporta un acabado brillante, sino que también refuerza la estructura del mate, asegurando mayor resistencia y durabilidad. Ideal para quienes buscan un mate único, de calidad superior y con un diseño detallado que destaca por su estilo refinado y moderno." },
  { id: 21, imagen: "/catalogo-siempremates//img/Mate-animalprint.jpg", nombre: "Mate imperial Animal Print interior calabaza virola alpaca", precio: "45.000", categoria: "Mates", descripcion: "El mate Imperial Animal Print de interior de calabaza con virola de alpaca es una opción audaz y sofisticada para quienes buscan un diseño único. La calabaza proporciona un sabor auténtico y mejora con el tiempo, mientras que el diseño animal print en su exterior le da un toque moderno y llamativo. La virola de alpaca refuerza la estructura del mate, brindando resistencia y un acabado brillante. Ideal para quienes desean un mate que combine la tradición con un diseño exclusivo y elegante, perfecto para destacar en cualquier ocasión." },




  { id: 22, imagen: "/catalogo-siempremates//img/bombilla1.png", nombre: "Bombilla pico de loro de acero inox", precio: "5.000", categoria: "Bombillas", descripcion: "La bombilla pico de loro de acero inoxidable es una opción práctica y elegante para disfrutar del mate. Su diseño largo y delgado, con una curva pronunciada, permite una fácil extracción de la yerba sin obstrucciones, lo que la hace ideal para mates de gran capacidad. El acero inoxidable le da resistencia, durabilidad y una fácil limpieza, además de ser resistente a la corrosión. Esta bombilla, gracias a su diseño funcional y materiales de alta calidad, es perfecta para quienes buscan comodidad y longevidad en sus accesorios de mate." },
  { id: 23, imagen: "/catalogo-siempremates//img/bombilla2.png", nombre: "Bombilla chata de acero inox", precio: "3.500", categoria: "Bombillas", descripcion: "" },
  { id: 24, imagen: "/catalogo-siempremates//img/bombilla3.png", nombre: "Bombillon de alpaca premium", precio: "28.500", categoria: "Bombillas", descripcion: "" },
  { id: 25, imagen: "/catalogo-siempremates//img/bombilla4.png", nombre: "Bombillon de alpaca club de futbol", precio: "22.000", categoria: "Bombillas", descripcion: "" },
  { id: 26, imagen: "/catalogo-siempremates//img/bombilla5.png", nombre: "Bombillon de alpaca premium con pico de bronce recto. caño labrado con 2 dijes ", precio: "30.000", categoria: "Bombillas", descripcion: "" },


  { id: 27, imagen: "/catalogo-siempremates//img/", nombre: "En proceso...", precio: "", categoria: "Termos", descripcion: "En proceso..." },

  { id: 28, imagen: "/catalogo-siempremates//img/", nombre: "En proceso...", precio: "", categoria: "Yerba", descripcion: "En proceso..." },

  { id: 29, imagen: "/catalogo-siempremates//img/Matera1.png", nombre: "Matera 100% cuero negra", precio: "40.000", categoria: "Bolsos", descripcion: "" },
  { id: 30, imagen: "/catalogo-siempremates//img/Matera2.png", nombre: "Matera 100% cuero marron claro", precio: "40.000", categoria: "Bolsos", descripcion: "" },
  { id: 31, imagen: "/catalogo-siempremates//img/Matera3.png.jpg", nombre: "Canasta cuerina grande premium reforzada con división", precio: "13.000", categoria: "Bolsos", descripcion: "" },
  { id: 32, imagen: "/catalogo-siempremates//img/Bolso1.jpg", nombre: "Bolso Matero", precio: "15.000", categoria: "Bolsos", descripcion: "" },
  { id: 33, imagen: "/catalogo-siempremates//img/Yerbero1.jpg", nombre: "Yerbero", precio: "5.000", categoria: "Bolsos", descripcion: "" },
  { id: 34, imagen: "/catalogo-siempremates//img/Azucarero1.jpg", nombre: "Azucarero", precio: "5.000", categoria: "Bolsos", descripcion: "" },





];

const ProductosLista = ({ categoria }) => {
  const productosFiltrados = Productos.filter((producto) => producto.categoria === categoria);

  return (
    <div className="productos-grid">
      {productosFiltrados.length > 0 ? (
        productosFiltrados.map((producto) => (
          <ProductoRnd
            key={producto.id}
            id={producto.id}
            imagen={producto.imagen}
            nombre={producto.nombre}
            precio={producto.precio}
            descripcion={producto.descripcion} // Pasamos la descripcion al componente
            sinExtras={false}
          />
        ))
      ) : (
        <p>No hay productos en esta categoría.</p>
      )}
    </div>
  );
};

export default ProductosLista;
